### ISSUE TITLE
Unittests failed

### ISSUE THREAD

**Issue by mvdstam** [cheprasov/php-redis-client#36]
Hello,

When running the testsuite, one test fails:

```
................................F

Time: 338 ms, Memory: 13.25Mb

There was 1 failure:

1) Test\Integration\Version2x6\KeysCommandsTest::test_pttl
Failed asserting that -2 is identical to -1.

~/Sites/php-redis-client/tests/Integration/Version2x6/KeysCommandsTest.php:292
```

**Comment by cheprasov** [comment]
Hello.
I ran the tests and they passed successfully.
What versions of Redis did you use for the tests?
Because, the error looks like you ran the tests for Redis 2.6.x on version above (>= 2.8.x).

Please, see here about pttl command [http://redis.io/commands/pttl](http://redis.io/commands/pttl)

> In Redis 2.6 or older the command returns -1 if the key does not exist or if the key exist but has no associated expire.
> Starting with Redis 2.8 the return value in case of error changed:
> The command returns -2 if the key does not exist.
> The command returns -1 if the key exists but has no associated expire.

For run all tests, we need use next Redis versions: **2.6.x**, **2.8.x**, **3.0.x**, **3.2-RCx**
You can find config in file [phpunit.xml](https://github.com/cheprasov/php-redis-client/blob/master/phpunit.xml)
```
<const name="TEST_REDIS_SERVER_2x6_1" value="tcp://127.0.0.1:6381" />
<const name="TEST_REDIS_SERVER_2x6_2" value="tcp://127.0.0.1:6382" />
<const name="TEST_REDIS_SERVER_2x8_1" value="tcp://127.0.0.1:6383" />
<const name="TEST_REDIS_SERVER_2x8_2" value="tcp://127.0.0.1:6384" />
<const name="TEST_REDIS_SERVER_3x0_1" value="tcp://127.0.0.1:6385" />
<const name="TEST_REDIS_SERVER_3x0_2" value="tcp://127.0.0.1:6386" />
<const name="TEST_REDIS_SERVER_3x2_1" value="tcp://127.0.0.1:6387" />
<const name="TEST_REDIS_SERVER_3x2_2" value="tcp://127.0.0.1:6388" />
```

Or you can use for tests a prepared [Docker container](https://hub.docker.com/r/cheprasov/redis-for-tests/) with the latest versions or Redis.

I hope, the issue is solved.

**Comment by cheprasov** [comment]
And I think, I will add checks of version in the tests. Thanks for help.

**Comment by mvdstam** [comment]
Thank you, looks good. :+1:
